### PR TITLE
US272Task288

### PR DESCRIPTION
**Pull request by vrupak**
Added the new logo and made a separate folder for images and updated the import image statements for few files.

### CODE REVIEW

**Review by atharva-date — APPROVED** [review]

**Comment by spark290** [comment]
Is this a commit into US272 from US272 Task288?
And can you unify the name of PR as previous ones?

**Comment by vrupak** [comment]
> Is this a commit into US272 from US272 Task288? And can you unify the name of PR as previous ones?

Its done now, Thanks!

**Review by AdvaitChirmule — APPROVED** [review]
Fix the branches please

**Comment by vrupak** [comment]
Going to fix rhe branches.

**Pull request closed without merging**
