### PR TITLE
[US266 Task308] Pass response data to chart for adopted work

### PR DESCRIPTION
**Pull request by atharva-date**
adpoted_work_data

### CODE REVIEW

**Comment by shahih25** [comment]
@atharva-date Can you delete this file? https://github.com/SER516-Clever/SER516-Team-Clever/blob/US266/react-ui/src/graph/testData.js#L2

https://github.com/SER516-Clever/SER516-Team-Clever/pull/21#discussion_r1571828495

**Comment by atharva-date** [comment]
@shahih25 Deleted the file

**Comment by shahih25** [comment]
Screenshot 2024-04-19 at 8 21 48 PM

**Review by shahih25 — APPROVED** [review]
lgtm

**Pull request merged**
